on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [ 'jep401ea2' ]
    name: Java ${{ matrix.release }}
    steps:
      - uses: actions/checkout@v3
      - name: setup
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: ${{ matrix.release }}
      - name: build
        run: |
          mvn -B package
